import "./globals.css";
import Menu from "./_components/MenuBar";
import DataProvider from "./_components/DataProvider";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <DataProvider>
          <header className="bg-gray-500 p-5 mb-5">
            <h1 className="text-center text-4xl text-white mb-4">
              Take input from users
            </h1>
            <div className="text-center text-2xl text-white">
              <Menu />
            </div>
          </header>

          <main>
            <div>
              {children}
            </div>
          </main>


          <footer className="bg-gray-500 text-center text-white p-4 bottom-0 fixed w-full">
            <p>
              &copy; Creat by Farzan :)
            </p>
          </footer>
        </DataProvider>
      </body>
    </html>
  )
}
